name: main-workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"

      - name: Print Go Version
        run: go version
      - name: Run unit test
        run: go test -v ./...

  build-and-release:
    runs-on: ubuntu-latest
    steps:

      - name: Check out source code
        uses: actions/checkout@v2


      - name: Build and push container image
        uses: docker/build-push-action@v2
        env:
          IMAGE_REPOSITORY: jjoseph18/foobar
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
        